### ISSUE TITLE
Admin Routes and Port

### ISSUE THREAD

**Issue by aydinnyunus** [dzungtran/echo-rest-api#42]
I did not find any valid web interface on 4434 which is for admin. 4434 is open but nothing shows. Maybe some configurations are wrong.

**Comment by dzungtran** [comment]
@aydinnyunus I don't know where you get this port `4434`.
But if you want to access Kratos login UI, you can try this address on local: `echo-rest.local:4455`

I have a guide for running this project on local in `README.md`

## Running the project

- Make sure you have docker installed.
- Copy `.env.example` to `.env.docker`
- Add a new line `127.0.0.1	echo-rest.local` to `/etc/hosts` file.
- Run `docker compose up -d`.
- Go to `echo-rest.local:8088` to verify if the API server works.
- Go to `echo-rest.local:4455` to verify if the Kratos works.
